development:
  adapter: postgresql
  database: baseapp_development
  username: whitemac
  password:
  encoding: utf8
  pool: 5

test: &test
  adapter: postgresql
  database: baseapp_test
  username: whitemac
  password:
  encoding: utf8
  pool: 5

cucumber:
  <<: *test
